/**
 * ─── Integration Provenance Types ──────────────────────────────────
 * Explicit truth layer for all hardware integration.
 * Every adapter and snapshot must declare its provenance.
 */

// How is this adapter currently operating?
export type IntegrationMode =
  | 'simulated'          // Synthetic data, no hardware link
  | 'replay'             // Playing back recorded logs
  | 'live_read_only'     // Passive feed from real device — no write
  | 'not_integrated';    // Declared but no data source at all

// Where does the data come from?
export type DataProvenance =
  | 'synthetic'              // Generated by adapter simulation code
  | 'imported_log'           // Loaded from a snapshot/log file
  | 'passive_device_feed'    // Ingested from a real device (read-only)
  | 'manual_entry';          // Operator typed it in

// How confident are we in the data?
export type EvidenceLevel =
  | 'ui_only'                // Data exists only in the UI layer
  | 'adapter_only'           // Adapter reports it but no external verification
  | 'telemetry_verified'     // Verified by telemetry ingestion pipeline
  | 'operator_confirmed';    // Human operator confirmed the state

// What physical transport connects to this device?
export type TransportType =
  | 'serial_usb'
  | 'spi'
  | 'analog_mux'
  | 'ethernet_udp'
  | 'ethernet_tcp'
  | 'wifi'
  | 'ble'
  | 'radio_433mhz'
  | 'logical'           // No physical transport (e.g. export profiles)
  | 'none';              // Not connected

/** Provenance info attached to every adapter */
export interface ProvenanceInfo {
  integration_mode: IntegrationMode;
  provenance: DataProvenance;
  evidence_level: EvidenceLevel;
  transport_type: TransportType;
  last_seen_at: number;           // timestamp ms
  data_freshness_ms: number;      // age of last data point
  writable: false;                // ALWAYS false — enforced at type level
}

/**
 * Default provenance for adapters with no real hardware backing.
 *
 * ⚠️  TESTING PHASE: returns `not_integrated` so the UI never shows
 * fake data as if it were real. Adapters that want explicit synthetic
 * data must call `createForcedSimulatedProvenance()` (gated behind a
 * dev-only flag — currently no callers).
 *
 * Original simulated semantics preserved at:
 *     src/_quarantine/safety/safetyGate.original.ts.txt
 */
export function createSimulatedProvenance(transport: TransportType = 'none'): ProvenanceInfo {
  return {
    integration_mode: 'not_integrated',
    provenance: 'synthetic',
    evidence_level: 'ui_only',
    transport_type: transport,
    last_seen_at: 0,
    data_freshness_ms: Infinity,
    writable: false,
  };
}

/** Explicit opt-in if a dev tool truly needs synthetic data. */
export function createForcedSimulatedProvenance(transport: TransportType = 'none'): ProvenanceInfo {
  return {
    integration_mode: 'simulated',
    provenance: 'synthetic',
    evidence_level: 'adapter_only',
    transport_type: transport,
    last_seen_at: Date.now(),
    data_freshness_ms: 0,
    writable: false,
  };
}

/** Default provenance for replay mode */
export function createReplayProvenance(): ProvenanceInfo {
  return {
    integration_mode: 'replay',
    provenance: 'imported_log',
    evidence_level: 'adapter_only',
    transport_type: 'none',
    last_seen_at: 0,
    data_freshness_ms: Infinity,
    writable: false,
  };
}

/** Check if data is stale (>10s default) */
export function isDataStale(provenance: ProvenanceInfo, thresholdMs: number = 10_000): boolean {
  if (provenance.integration_mode === 'simulated') return false; // simulated is never "stale"
  if (provenance.integration_mode === 'not_integrated') return true;
  return provenance.data_freshness_ms > thresholdMs;
}

/** Human-readable badge label */
export function getProvenanceBadge(mode: IntegrationMode): { label: string; color: string } {
  switch (mode) {
    case 'simulated': return { label: 'SIMULATED', color: 'blue' };
    case 'replay': return { label: 'REPLAY', color: 'amber' };
    case 'live_read_only': return { label: 'LIVE READ-ONLY', color: 'emerald' };
    case 'not_integrated': return { label: 'NOT INTEGRATED', color: 'red' };
  }
}

// ─── Real-Only Handshake Helpers ──────────────────────────────────
//
// In real-only mode (default), an adapter stays `not_integrated` until
// the physical device responds to a handshake (firmware reply, ArtPoll
// reply, BLE characteristic read, etc.). Only after `markHandshakeOk`
// does the adapter transition to `live_read_only` and become eligible
// to emit telemetry / events.

/** Promote provenance to live_read_only after a verified device reply. */
export function markHandshakeOk(
  prov: ProvenanceInfo,
  transport: TransportType = prov.transport_type,
): ProvenanceInfo {
  prov.integration_mode = 'live_read_only';
  prov.provenance = 'passive_device_feed';
  prov.evidence_level = 'telemetry_verified';
  prov.transport_type = transport;
  prov.last_seen_at = Date.now();
  prov.data_freshness_ms = 0;
  return prov;
}

/** Reset provenance back to not_integrated after disconnect / timeout. */
export function markHandshakeLost(prov: ProvenanceInfo): ProvenanceInfo {
  prov.integration_mode = 'not_integrated';
  prov.provenance = 'synthetic';
  prov.evidence_level = 'ui_only';
  prov.last_seen_at = 0;
  prov.data_freshness_ms = Infinity;
  return prov;
}

/**
 * Is this provenance allowed to emit data in real-only mode?
 * `live_read_only` and `replay` are accepted; everything else is blocked.
 */
export function isProvenanceVerified(prov: ProvenanceInfo): boolean {
  return prov.integration_mode === 'live_read_only'
    || prov.integration_mode === 'replay';
}
