/**
 * ─── Integration Provenance Types ──────────────────────────────────
 * Explicit truth layer for all hardware integration.
 * Every adapter and snapshot must declare its provenance.
 */

// How is this adapter currently operating?
export type IntegrationMode =
  | 'simulated'          // Synthetic data, no hardware link
  | 'replay'             // Playing back recorded logs
  | 'live_read_only'     // Passive feed from real device — no write
  | 'not_integrated';    // Declared but no data source at all

// Where does the data come from?
export type DataProvenance =
  | 'synthetic'              // Generated by adapter simulation code
  | 'imported_log'           // Loaded from a snapshot/log file
  | 'passive_device_feed'    // Ingested from a real device (read-only)
  | 'manual_entry';          // Operator typed it in

// How confident are we in the data?
export type EvidenceLevel =
  | 'ui_only'                // Data exists only in the UI layer
  | 'adapter_only'           // Adapter reports it but no external verification
  | 'telemetry_verified'     // Verified by telemetry ingestion pipeline
  | 'operator_confirmed';    // Human operator confirmed the state

// What physical transport connects to this device?
export type TransportType =
  | 'serial_usb'
  | 'spi'
  | 'analog_mux'
  | 'ethernet_udp'
  | 'ethernet_tcp'
  | 'wifi'
  | 'ble'
  | 'radio_433mhz'
  | 'logical'           // No physical transport (e.g. export profiles)
  | 'none';              // Not connected

/** Provenance info attached to every adapter */
export interface ProvenanceInfo {
  integration_mode: IntegrationMode;
  provenance: DataProvenance;
  evidence_level: EvidenceLevel;
  transport_type: TransportType;
  last_seen_at: number;           // timestamp ms
  data_freshness_ms: number;      // age of last data point
  writable: false;                // ALWAYS false — enforced at type level
}

/** Default provenance for simulated adapters */
export function createSimulatedProvenance(transport: TransportType = 'none'): ProvenanceInfo {
  return {
    integration_mode: 'simulated',
    provenance: 'synthetic',
    evidence_level: 'adapter_only',
    transport_type: transport,
    last_seen_at: Date.now(),
    data_freshness_ms: 0,
    writable: false,
  };
}

/** Default provenance for replay mode */
export function createReplayProvenance(): ProvenanceInfo {
  return {
    integration_mode: 'replay',
    provenance: 'imported_log',
    evidence_level: 'adapter_only',
    transport_type: 'none',
    last_seen_at: 0,
    data_freshness_ms: Infinity,
    writable: false,
  };
}

/** Check if data is stale (>10s default) */
export function isDataStale(provenance: ProvenanceInfo, thresholdMs: number = 10_000): boolean {
  if (provenance.integration_mode === 'simulated') return false; // simulated is never "stale"
  if (provenance.integration_mode === 'not_integrated') return true;
  return provenance.data_freshness_ms > thresholdMs;
}

/** Human-readable badge label */
export function getProvenanceBadge(mode: IntegrationMode): { label: string; color: string } {
  switch (mode) {
    case 'simulated': return { label: 'SIMULATED', color: 'blue' };
    case 'replay': return { label: 'REPLAY', color: 'amber' };
    case 'live_read_only': return { label: 'LIVE READ-ONLY', color: 'emerald' };
    case 'not_integrated': return { label: 'NOT INTEGRATED', color: 'red' };
  }
}
