/**
 * ─── FireOne Import Package ────────────────────────────────────────
 * Bundles every artefact a FireOne XLII+ / XL4-3 operator needs in a
 * single ZIP:
 *
 *   <show>.csv               — UltraFire CSV (File ▸ Import ▸ CSV File)
 *   <show>_positions.csv     — Position ↔ Slat map ("By Position" view)
 *   <show>_audit.txt         — Human audit log (NOT for import)
 *   _FXK_FIREONE_README.md   — Operator step-by-step
 *   _FXK_DISCLAIMER.txt      — Standard claim policy disclaimer
 *
 * Returns the same FireOneCsvResult so the UI can surface
 * cueCount / blocked / errors / warnings.
 */

import JSZip from 'jszip';
import { generateFireOneCsv, type FireOneCsvResult } from './FireOneCsvExporter';
import { generateFireOneScript } from './FireOneExporter';
import { showPlanManager } from '@/core/showplan/ShowPlanManager';
import { recordSafetyNote } from '@/core/safety/safetyBlackBox';

const README = (showName: string, planHash: string) => `# FireOne XLII+ / XL4-3 — Import Package

Show: **${showName}**
Plan hash: \`${planHash}\`

## How to import in UltraFire (desktop)

1. Open UltraFire and create / open the target show file (\`.sem\`).
2. \`File ▸ Import ▸ CSV File\` and select **${showName}.csv**.
3. Verify the slat / cue grid matches **${showName}_positions.csv**.
4. Connect the FireOne XLII+ controller via USB-FTDI (9600 8N1).
5. Use UltraFire's \`Tools ▸ Download to Modules\` to push the show.

## What is in this ZIP

- **${showName}.csv** — the only file UltraFire imports.
- **${showName}_positions.csv** — companion map (positions ↔ slat/cue).
- **${showName}_audit.txt** — human-readable log; **do NOT import**.
- **_FXK_DISCLAIMER.txt** — claim policy.

## Generated by

FX KONTROL · ${new Date().toISOString()}
`;

const DISCLAIMER = `FX KONTROL — FireOne Export Disclaimer

This package was generated by FX KONTROL and converted from the canonical
ShowPlan to the UltraFire CSV format documented in the FireOne XLII+ user
guide. Operator is responsible for:

  • Validating slat / cue assignment on hardware before show.
  • Performing continuity check (UltraFire ▸ Tools ▸ Continuity).
  • Following NFPA 1123 / local fire-marshal regulations.

FX KONTROL is **not** a substitute for on-site safety procedures.
`;

function positionsCsv(): string {
  const sp = showPlanManager.current;
  const lines = ['Position,Slat,Cue,Caliber,Elevation,Section'];
  const sorted = [...sp.pyroCues].sort((a, b) => a.module - b.module || a.channel - b.channel);
  for (const cue of sorted) {
    const pos = sp.positions.find(p => p.id === cue.positionId);
    lines.push([
      pos?.name ?? cue.positionId ?? '',
      (cue.module ?? 0) + 1,
      (cue.channel ?? 0) + 1,
      `${cue.caliber}mm`,
      cue.elevation.toFixed(1),
      cue.section ?? '',
    ].join(','));
  }
  return lines.join('\r\n') + '\r\n';
}

function safeName(name: string): string {
  return (name || 'fxk_show').replace(/[^\w\-]+/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
}

export interface FireOneImportPackageResult extends FireOneCsvResult {
  zipBlob: Blob;
  zipFilename: string;
}

export async function buildFireOneImportPackage(): Promise<FireOneImportPackageResult> {
  const sp = showPlanManager.current;
  const showName = safeName(sp.metadata.name);
  const csv = generateFireOneCsv();
  const audit = generateFireOneScript();

  const zip = new JSZip();
  zip.file(`${showName}.csv`, csv.csv);
  zip.file(`${showName}_positions.csv`, positionsCsv());
  zip.file(`${showName}_audit.txt`, audit.script);
  zip.file('_FXK_FIREONE_README.md', README(sp.metadata.name, csv.planHash));
  zip.file('_FXK_DISCLAIMER.txt', DISCLAIMER);

  const zipBlob = await zip.generateAsync({ type: 'blob', compression: 'DEFLATE' });
  void recordSafetyNote('fireone-import-package', {
    planHash: csv.planHash,
    cueCount: csv.cueCount,
    slats: csv.slats,
    bytes: zipBlob.size,
  });

  return { ...csv, zipBlob, zipFilename: `${showName}_FIREONE.zip` };
}

export async function downloadFireOneImportPackage(): Promise<FireOneImportPackageResult> {
  const r = await buildFireOneImportPackage();
  const url = URL.createObjectURL(r.zipBlob);
  const a = document.createElement('a');
  a.href = url;
  a.download = r.zipFilename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
  return r;
}
