/**
 * useExecutiveReport — writer for public.executive_reports.
 *
 * Reports are the show-level readiness snapshot generated by the
 * VerificationEngine before a real-show transition (preflight → armed).
 * Persisted so a post-show audit can replay the exact readiness state
 * the operator saw at the moment of go/no-go.
 *
 * Failure mode: same as the journal writer — never blocks the UI.
 */
import { useCallback } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { useUIWorkspaceStore } from '@/stores/uiWorkspaceStore';

export type ReadinessStatus = 'READY' | 'BLOCKED' | 'WARNING' | 'UNKNOWN';
export type VerificationLevel =
  | 'READY_FOR_SIMULATION'
  | 'READY_FOR_EXPORT'
  | 'READY_FOR_LIVE'
  | 'BLOCKED';

export interface ExecutiveReportInput {
  show_name: string;
  readiness_status: ReadinessStatus;
  verification_level: VerificationLevel;
  /** Full structured report — kept opaque to this hook on purpose. */
  report_data: Record<string, unknown>;
}

export function useExecutiveReport() {
  const addLocal = useUIWorkspaceStore((s) => s.addExecutiveReport);

  const submit = useCallback(async (input: ExecutiveReportInput): Promise<string | null> => {
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) {
      // Mirror locally even if not authenticated so the operator sees it,
      // but don't persist (RLS would reject and we don't want a noisy log).
      addLocal({
        id: `local-${Date.now()}`,
        showName: input.show_name,
        readinessStatus: input.readiness_status,
      });
      return null;
    }

    const { data, error } = await supabase
      .from('executive_reports')
      .insert({
        user_id: user.id,
        show_name: input.show_name,
        readiness_status: input.readiness_status,
        verification_level: input.verification_level,
        report_data: input.report_data,
      })
      .select('id')
      .single();

    if (error || !data) {
      if (typeof console !== 'undefined') {
        console.warn('[executive_reports] persist failed:', error?.message ?? 'no data');
      }
      addLocal({
        id: `local-${Date.now()}`,
        showName: input.show_name,
        readinessStatus: input.readiness_status,
      });
      return null;
    }

    addLocal({
      id: data.id,
      showName: input.show_name,
      readinessStatus: input.readiness_status,
    });
    return data.id;
  }, [addLocal]);

  return submit;
}
