/**
 * FWsim Graphics Tuning — canonical accessor
 *
 * Wraps the JSON generated by `scripts/parse-fwsim-graphics.mjs` from the
 * upstream `public/fwsim/graphics.xml` (FWsim 3.4.x).
 *
 * Data-only: NO render-side wiring is forced. Renderers opt-in via
 * feature flags (see src/lib/featureFlags.ts: r_fwsim_*).
 *
 * Source: graphics.xml authored by Lukas/Marcus (FWsim team).
 */
import raw from './fwsimGraphicsConfig.json';

export type FwsimGraphicsConfig = typeof raw;
export type FwsimStarTypeEnum =
  | 'XLarge' | 'Large' | 'Normal' | 'Small' | 'XSmall' | 'XXSmall'
  | 'Sparks' | 'FallingLeaves';
export type FwsimTailTypeEnum =
  | 'Sparks' | 'Microstars_Small' | 'Microstars_Medium' | 'Microstars_Large';

export interface FwsimDataPoint {
  /** Input value (e.g. launch energy, shell size in mm, or normalized 0..1 time). */
  x: number;
  /** Output value at x. */
  y: number;
}

let _cached: FwsimGraphicsConfig | null = null;

/** Memoized canonical FWsim graphics config. Pure read; never mutate. */
export function getFwsimGraphics(): FwsimGraphicsConfig {
  if (_cached) return _cached;
  _cached = raw as FwsimGraphicsConfig;
  return _cached;
}

/** Resolve a single FWsim preset color by name → `#rrggbb`. Returns null if unknown. */
export function getFwsimPresetHex(name: string): string | null {
  const palette = (getFwsimGraphics().presetColors as Record<string, [number, number, number]>);
  const v = palette[name];
  if (!v) return null;
  const [r, g, b] = v;
  const hex = (n: number) => Math.max(0, Math.min(255, n | 0)).toString(16).padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(b)}`;
}

/** Linear interpolation across a sorted DataPoint curve `[ [x,y], ... ]`. Clamps at edges. */
export function sampleCurve(pts: ReadonlyArray<readonly [number, number]>, x: number): number {
  if (!pts.length) return 0;
  if (x <= pts[0][0]) return pts[0][1];
  if (x >= pts[pts.length - 1][0]) return pts[pts.length - 1][1];
  for (let i = 1; i < pts.length; i++) {
    const [x1, y1] = pts[i];
    if (x <= x1) {
      const [x0, y0] = pts[i - 1];
      const t = (x - x0) / (x1 - x0 || 1);
      return y0 + (y1 - y0) * t;
    }
  }
  return pts[pts.length - 1][1];
}

/** Path to the canonical smoke sprite (FWsim sourced). Import via `@/assets/textures/fwsim/...`. */
export const FWSIM_SMOKE_TEXTURE_PATH =
  'src/assets/textures/fwsim/smoke_with_alpha.png';
