/**
 * FWsim Graphics Tuning — canonical accessor
 *
 * Wraps the JSON generated by `scripts/parse-fwsim-graphics.mjs` from the
 * upstream `public/fwsim/graphics.xml` (FWsim 3.4.x).
 *
 * Data-only: NO render-side wiring is forced. Renderers opt-in via
 * feature flags (see src/lib/featureFlags.ts: r_fwsim_*).
 *
 * Source: graphics.xml authored by Lukas/Marcus (FWsim team).
 */
import raw from './fwsimGraphicsConfig.json';

export type FwsimGraphicsConfig = typeof raw;
export type FwsimStarTypeEnum =
  | 'XLarge' | 'Large' | 'Normal' | 'Small' | 'XSmall' | 'XXSmall'
  | 'Sparks' | 'FallingLeaves';
export type FwsimTailTypeEnum =
  | 'Sparks' | 'Microstars_Small' | 'Microstars_Medium' | 'Microstars_Large';

export interface FwsimDataPoint {
  /** Input value (e.g. launch energy, shell size in mm, or normalized 0..1 time). */
  x: number;
  /** Output value at x. */
  y: number;
}

let _cached: FwsimGraphicsConfig | null = null;

/** Memoized canonical FWsim graphics config. Pure read; never mutate. */
export function getFwsimGraphics(): FwsimGraphicsConfig {
  if (_cached) return _cached;
  _cached = raw as FwsimGraphicsConfig;
  return _cached;
}

/** Resolve a single FWsim preset color by name → `#rrggbb`. Returns null if unknown. */
export function getFwsimPresetHex(name: string): string | null {
  const palette = getFwsimGraphics().presetColors as unknown as Record<string, [number, number, number]>;
  const v = palette[name];
  if (!v) return null;
  const [r, g, b] = v;
  const hex = (n: number) => Math.max(0, Math.min(255, n | 0)).toString(16).padStart(2, '0');
  return `#${hex(r)}${hex(g)}${hex(b)}`;
}

/** Linear interpolation across a sorted DataPoint curve `[ [x,y], ... ]`. Clamps at edges. */
export function sampleCurve(pts: ReadonlyArray<readonly [number, number]>, x: number): number {
  if (!pts.length) return 0;
  if (x <= pts[0][0]) return pts[0][1];
  if (x >= pts[pts.length - 1][0]) return pts[pts.length - 1][1];
  for (let i = 1; i < pts.length; i++) {
    const [x1, y1] = pts[i];
    if (x <= x1) {
      const [x0, y0] = pts[i - 1];
      const t = (x - x0) / (x1 - x0 || 1);
      return y0 + (y1 - y0) * t;
    }
  }
  return pts[pts.length - 1][1];
}

/** Path to the canonical smoke sprite (FWsim sourced). Import via `@/assets/textures/fwsim/...`. */
export const FWSIM_SMOKE_TEXTURE_PATH =
  'src/assets/textures/fwsim/smoke_with_alpha.png';

/**
 * Derived calibration factors for the legacy Bloom pipeline.
 *
 * Maps FWsim's bloom config (graphics.xml) into renderer-side multipliers:
 *  - `intensityMul` = `amountOfBloom × avg(upsamplingWeights)` (FWsim sums weighted mip contributions;
 *    the average weight × bloom amount approximates the integrated bloom energy per pixel).
 *  - `levels` mirrors `nrLevels` (FWsim default 10) — drives kernel choice.
 *  - `radius` mirrors `radiusForUpsampling` (default 1.5).
 *
 * Pure read; safe to call in render loops (memoised on getFwsimGraphics()).
 */
export function getFwsimBloomCalibration(): {
  intensityMul: number;
  levels: number;
  radius: number;
  weightsAvg: number;
  amount: number;
} {
  const b = getFwsimGraphics().bloom as unknown as {
    amountOfBloom?: number;
    upsamplingWeights?: number[];
    nrLevels?: number;
    radiusForUpsampling?: number;
  };
  const amount = typeof b.amountOfBloom === 'number' ? b.amountOfBloom : 0.1;
  const weights = Array.isArray(b.upsamplingWeights) && b.upsamplingWeights.length > 0
    ? b.upsamplingWeights
    : [1];
  const weightsAvg = weights.reduce((s, w) => s + w, 0) / weights.length;
  // Clamp to a sane range so a malformed config can't blow out the renderer.
  const intensityMul = Math.max(0.25, Math.min(4.0, amount * weightsAvg * 10)); // ×10 normaliza amount=0.1 → ~weightsAvg
  const levels = Math.max(1, Math.min(16, Math.round(b.nrLevels ?? 10)));
  const radius = Math.max(0.5, Math.min(4.0, b.radiusForUpsampling ?? 1.5));
  return { intensityMul, levels, radius, weightsAvg, amount };
}
